# Generated by Django 5.1 on 2024-08-21 18:45

from django.utils import timezone

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("enrollment_date", models.DateField()),
            ],
        ),
    migrations.AddField(
    model_name='course',
    name='created_at',
    field=models.DateTimeField(auto_now_add=True, default=timezone.now),
    preserve_default=False,
)


    ]
